import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        // Suppress hydration warnings caused by browser extensions (e.g., Grammarly)
        // adding attributes like data-new-gr-c-s-check-loaded / data-gr-ext-installed on the client only.
        // See: https://react.dev/link/hydration-mismatch
        className={`${geistSans.variable} ${geistSans.className} ${geistMono.variable} w-full bg-base-300 antialiased`}
      >
        <NextTopLoader showSpinner={false} color="#009764" />
        {children}
      </body>
    </html>
  );
}
