"use client";

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { format } from "date-fns";
import { registerGeistFont } from "./fonts/geist-pdf";

export interface PdfColumn {
  header: string;
  dataKey: string;
  width?: number;
}

export interface PdfExportOptions {
  title: string;
  data: Record<string, unknown>[];
  columns: PdfColumn[];
  filename?: string;
  subtitle?: string;
  generatedBy?: { name: string; email?: string };
}

// --color-primary: oklch(59% 0.145 163.225) from globals.css → teal/green, matches #009764 used in app
const PRIMARY_COLOR: [number, number, number] = [0, 151, 100];
const TEXT_COLOR: [number, number, number] = [29, 29, 31]; // #1d1d1f - matches --color-base-content
const MUTED_COLOR: [number, number, number] = [134, 134, 139]; // #86868b - matches --color-muted

export function exportToPDF({
  title,
  data,
  columns,
  filename,
  subtitle,
  generatedBy,
}: PdfExportOptions) {
  const doc = new jsPDF();
  registerGeistFont(doc);
  doc.setFont("GeistSans", "normal");

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  const headerText = "AI'll Be Sick";
  doc.setFontSize(10);
  doc.setTextColor(...MUTED_COLOR);
  doc.text(headerText, 14, 15);

  doc.setFontSize(20);
  doc.setFont("GeistSans", "bold");
  doc.setTextColor(...TEXT_COLOR);
  doc.text(title, 14, 28);
  doc.setFont("GeistSans", "normal");

  let currentY = 36;
  if (subtitle) {
    doc.setFontSize(10);
    doc.setTextColor(...MUTED_COLOR);
    doc.text(subtitle, 14, currentY);
    currentY += 6;
  }

  const generatedDate = format(new Date(), "MMMM d, yyyy 'at' h:mm a");
  if (generatedBy) {
    doc.setFontSize(8);
    doc.setTextColor(...MUTED_COLOR);
    const byLine = generatedBy.email
      ? `Generated by: ${generatedBy.name} (${generatedBy.email})`
      : `Generated by: ${generatedBy.name}`;
    doc.text(byLine, 14, currentY);
    currentY += 5;
    doc.text(`Generated on: ${generatedDate}`, 14, currentY);
    currentY += 8;
  }

  doc.setFontSize(8);
  doc.setTextColor(...MUTED_COLOR);
  doc.text(`Generated on ${generatedDate}`, 14, pageHeight - 10);

  const tableData = data.map((row) =>
    columns.map((col) => {
      const value = row[col.dataKey];
      if (value === null || value === undefined) return "-";
      if (typeof value === "number") {
        if (col.dataKey.toLowerCase().includes("confidence") || col.dataKey.toLowerCase().includes("uncertainty")) {
          return `${(value * 100).toFixed(1)}%`;
        }
        return value.toString();
      }
      if (value instanceof Date) {
        return format(value, "MMM d, yyyy");
      }
      if (typeof value === "object" && "toString" in value) {
        return value.toString();
      }
      return String(value);
    })
  );

  const tableStartY = generatedBy ? currentY : subtitle ? 42 : 38;

  autoTable(doc, {
    head: [columns.map((col) => col.header)],
    body: tableData,
    startY: tableStartY,
    headStyles: {
      font: "GeistSans",
      fontStyle: "bold",
      fillColor: PRIMARY_COLOR,
      textColor: [255, 255, 255],
      fontSize: 10,
      halign: "left",
    },
    bodyStyles: {
      font: "GeistSans",
      fontSize: 9,
      textColor: TEXT_COLOR,
      halign: "left",
    },
    alternateRowStyles: {
      fillColor: [245, 245, 247],
    },
    columnStyles: columns.reduce((acc, col, idx) => {
      if (col.width) {
        acc[idx] = { cellWidth: col.width };
      }
      return acc;
    }, {} as Record<number, { cellWidth?: number }>),
    margin: { left: 14, right: 14 },
    theme: "striped",
    styles: {
      font: "GeistSans",
      lineColor: [232, 232, 237],
      lineWidth: 0.1,
    },
  });

  const finalY = (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? 0;
  
  doc.setFontSize(8);
  doc.setTextColor(...MUTED_COLOR);
  doc.text(
    `Page 1 of ${doc.getNumberOfPages()}`,
    pageWidth / 2,
    pageHeight - 10,
    { align: "center" }
  );

  const base = filename || title.toLowerCase().replace(/\s+/g, "-");
  const safeFilename = base.endsWith(".pdf") ? base : `${base}.pdf`;
  doc.save(safeFilename);
}
