"""
Evidence keywords mapping for follow-up question deduplication.

Maps question IDs to lists of keywords (EN + TL) that indicate
prior evidence in the patient's symptom description.
"""

EVIDENCE_KEYWORDS = {
    # Typhoid (English + Tagalog)
    "typhoid_q1": [
        "belly pain",
        "stomach pain",
        "abdominal pain",
        "abdomen pain",
        "stomach ache",
        "belly ache",
        "sakit ng tiyan",
        "pananakit ng tiyan",
        "masakit ang tiyan",
        "tiyan",
        "puson",
        "sikmura",
    ],
    "typhoid_q2": [
        "constipation",
        "diarrhea",
        "diarrhoea",
        "loose stool",
        "watery stool",
        "alternating",
        "pagtatae",
        "pagtitibi",
        "tibi",
        "dumi",
        "tae",
    ],
    "typhoid_q3": [
        "fever",
        "high fever",
        "night fever",
        "evening fever",
        "lagnat",
        "mataas na lagnat",
        "nilalagnat",
        "temperatura",
    ],
    "typhoid_q4": [
        "chills",
        "shivering",
        "cold",
        "shaking",
        "panginginig",
        "ginaw",
        "giniginaw",
        "nanginginig",
    ],
    "typhoid_q5": [
        "nausea",
        "vomit",
        "vomiting",
        "feel like vomiting",
        "urge to vomit",
        "throwing up",
        "suka",
        "nagsusuka",
        "pagsusuka",
        "nasusuka",
        "pagduduwal",
    ],
    "typhoid_q6": [
        "loss of appetite",
        "lost appetite",
        "no appetite",
        "don't want to eat",
        "weight loss",
        "losing weight",
        "nawalan ng gana",
        "walang gana",
        "ayaw kumain",
    ],
    "typhoid_q7": [
        "fatigue",
        "tired",
        "weak",
        "exhausted",
        "weakness",
        "pagod",
        "napapagod",
        "mahina",
        "panghihina",
        "pagkapagod",
    ],
    "typhoid_q8": [
        "dehydrated",
        "dehydration",
        "trouble staying hydrated",
        "hard to stay hydrated",
        "thirsty",
        "uhaw",
        "tuyo",
    ],
    "typhoid_q9": [
        "headache",
        "head ache",
        "head pain",
        "sakit ng ulo",
        "pananakit ng ulo",
        "masakit ang ulo",
    ],
    "typhoid_q10": [
        "trouble sleeping",
        "can't sleep",
        "difficulty sleeping",
        "hard to sleep",
        "insomnia",
        "nahihirapan matulog",
        "hindi makatulog",
    ],
    # Dengue (English + Tagalog)
    "dengue_q1": [
        "pain",
        "painful",
        "discomfort",
        "ache",
        "aching",
        "hurt",
        "sore",
        "masakit",
        "pananakit",
        "sakit",
        "kirot",
    ],
    "dengue_q2": [
        "joint pain",
        "muscle pain",
        "body pain",
        "body ache",
        "muscle ache",
        "joint ache",
        "joints",
        "muscles",
        "kalamnan",
        "buto",
        "katawan",
    ],
    "dengue_q3": [
        "fever",
        "high fever",
        "temperature",
        "feverish",
        "lagnat",
        "mataas na lagnat",
        "nilalagnat",
        "temperatura",
    ],
    "dengue_q4": [
        "rash",
        "red spots",
        "skin rash",
        "spots",
        "skin eruption",
        "pantal",
        "pula",
        "pulang spot",
    ],
    "dengue_q5": [
        "redness",
        "red skin",
        "inflamed",
        "inflammation",
        "swelling",
        "pula",
        "namumula",
        "pamumula",
        "pamamaga",
    ],
    "dengue_q6": [
        "eye pain",
        "pain behind eyes",
        "retro-orbital",
        "eyes hurt",
        "mata",
        "pananakit ng mata",
        "likod ng mata",
        "masakit ang mata",
    ],
    "dengue_q7": [
        "chills",
        "shivering",
        "cold",
        "freezing",
        "shaking",
        "panginginig",
        "ginaw",
        "giniginaw",
        "nanginginig",
    ],
    "dengue_q8": [
        "nausea",
        "vomit",
        "vomiting",
        "feel like vomiting",
        "urge to vomit",
        "throwing up",
        "suka",
        "nagsusuka",
        "pagsusuka",
        "nasusuka",
        "pagduduwal",
    ],
    "dengue_q9": [
        "fatigue",
        "tired",
        "weak",
        "exhausted",
        "weakness",
        "pagod",
        "napapagod",
        "mahina",
        "panghihina",
    ],
    "dengue_q10": [
        "headache",
        "head ache",
        "head pain",
        "sakit ng ulo",
        "pananakit ng ulo",
        "masakit ang ulo",
    ],
    # Pneumonia (English + Tagalog)
    "pneumonia_q1": [
        "mucus",
        "phlegm",
        "sputum",
        "thick",
        "coughing up",
        "plema",
        "sipon",
    ],
    "pneumonia_q2": [
        "sweat",
        "sweating",
        "perspiration",
        "heavy sweating",
        "pawis",
        "pinagpapawisan",
        "pagpapawis",
    ],
    "pneumonia_q3": [
        "chest pain",
        "pain when breathing",
        "pain when coughing",
        "chest hurt",
        "chest discomfort",
        "dibdib",
        "pananakit ng dibdib",
        "masakit ang dibdib",
        "sakit ng dibdib",
    ],
    "pneumonia_q4": [
        "pain",
        "painful",
        "body pain",
        "ache",
        "masakit",
        "pananakit",
        "sakit",
    ],
    "pneumonia_q5": [
        "fatigue",
        "tired",
        "weak",
        "exhausted",
        "weakness",
        "pagod",
        "napapagod",
        "mahina",
        "panghihina",
    ],
    "pneumonia_q6": [
        "chills",
        "cold",
        "shivering",
        "shaking",
        "panginginig",
        "ginaw",
        "giniginaw",
        "nanginginig",
    ],
    "pneumonia_q7": [
        "cough",
        "coughing",
        "persistent cough",
        "ubo",
        "umuubo",
        "inuubo",
    ],
    "pneumonia_q8": [
        "fever",
        "high fever",
        "temperature",
        "lagnat",
        "mataas na lagnat",
        "nilalagnat",
    ],
    "pneumonia_q9": [
        "shortness of breath",
        "difficulty breathing",
        "rapid breathing",
        "hard to breathe",
        "breathless",
        "breathing",
        "breath",
        "hininga",
        "hinga",
        "paghinga",
        "hirap huminga",
        "nahihirapan huminga",
    ],
    "pneumonia_q10": [
        "joint pain",
        "muscle pain",
        "joints",
        "muscles",
        "kalamnan",
        "buto",
    ],
    # Diarrhea (English + Tagalog)
    "diarrhea_q1": [
        "watery",
        "loose",
        "liquid",
        "stool",
        "poop",
        "bowel",
        "dumi",
        "tae",
        "matubig",
        "malabnaw",
    ],
    "diarrhea_q2": [
        "blood",
        "bloody",
        "stools",
        "dugo",
        "madugo",
        "may dugo",
    ],
    "diarrhea_q3": [
        "stomach pain",
        "abdominal pain",
        "cramps",
        "stomach ache",
        "belly pain",
        "tiyan",
        "sakit ng tiyan",
        "pulikat",
        "kabag",
    ],
    "diarrhea_q4": [
        "thirsty",
        "dry mouth",
        "dehydrated",
        "dehydration",
        "uhaw",
        "tuyo ang bibig",
        "tuyot",
    ],
    "diarrhea_q5": [
        "fever",
        "high fever",
        "temperature",
        "lagnat",
        "sinat",
        "mainit",
    ],
    "diarrhea_q6": [
        "nausea",
        "vomit",
        "vomiting",
        "suka",
        "nagsusuka",
        "nasusuka",
        "duwal",
    ],
    "diarrhea_q7": [
        "mucus",
        "slime",
        "slimy",
        "uhog",
        "madulas",
    ],
    "diarrhea_q8": [
        "urgent",
        "urgency",
        "bathroom",
        "cr",
        "toilet",
        "banyo",
    ],
    "diarrhea_q9": [
        "weak",
        "weakness",
        "tired",
        "fatigue",
        "hina",
        "nanghihina",
        "pagod",
    ],
    "diarrhea_q10": [
        "appetite",
        "eat",
        "food",
        "gana",
        "kain",
    ],
    # Measles (English + Tagalog)
    "measles_q1": [
        "rash",
        "spots",
        "face",
        "pantal",
        "pula",
        "mukha",
    ],
    "measles_q2": [
        "fever",
        "high fever",
        "lagnat",
        "mataas na lagnat",
    ],
    "measles_q3": [
        "cough",
        "coughing",
        "dry cough",
        "ubo",
        "umuubo",
        "inuubo",
    ],
    "measles_q4": [
        "runny nose",
        "coryza",
        "sipon",
        "tumutulo ang sipon",
    ],
    "measles_q5": [
        "red eyes",
        "watery eyes",
        "conjunctivitis",
        "pula ang mata",
        "mata",
    ],
    "measles_q6": [
        "white spots",
        "mouth",
        "spots in mouth",
        "koplik",
        "puti",
        "bibig",
    ],
    "measles_q7": [
        "light",
        "sensitive",
        "eyes",
        "ilaw",
        "silaw",
        "liwanag",
    ],
    "measles_q8": [
        "muscle pain",
        "body pain",
        "ache",
        "sakit ng katawan",
        "kalamnan",
    ],
    "measles_q9": [
        "sore throat",
        "throat",
        "lalamunan",
        "masakit ang lalamunan",
    ],
    "measles_q10": [
        "tired",
        "fatigue",
        "pagod",
        "hina",
    ],
    # Influenza (English + Tagalog)
    "influenza_q1": [
        "sudden",
        "abrupt",
        "suddenly",
        "fever",
        "bigla",
        "lagnat",
    ],
    "influenza_q2": [
        "muscle ache",
        "body ache",
        "severe pain",
        "sakit ng katawan",
        "kalamnan",
        "ngalay",
    ],
    "influenza_q3": [
        "chills",
        "sweat",
        "shivering",
        "ginaw",
        "nanginginig",
        "pawis",
    ],
    "influenza_q4": [
        "dry cough",
        "cough",
        "ubo",
    ],
    "influenza_q5": [
        "fatigue",
        "exhausted",
        "tired",
        "pagod",
        "hapo",
        "hina",
    ],
    "influenza_q6": [
        "headache",
        "head pain",
        "sakit ng ulo",
    ],
    "influenza_q7": [
        "sore throat",
        "lalamunan",
    ],
    "influenza_q8": [
        "runny nose",
        "stuffy nose",
        "blocked nose",
        "sipon",
        "barado",
    ],
    "influenza_q9": [
        "eye pain",
        "behind eyes",
        "sakit ng mata",
    ],
    "influenza_q10": [
        "vomit",
        "diarrhea",
        "suka",
        "tae",
        "dudumi",
    ],
}
