"""
Evidence keywords mapping for follow-up question deduplication.

Maps question IDs to lists of keywords (EN + TL) that indicate
prior evidence in the patient's symptom description.

Keywords should be specific phrases, not single generic words.
This reduces false positives from generic terms like "pain" or "fever".
"""

EVIDENCE_KEYWORDS = {
    # ── Typhoid ──────────────────────────────────────────────────────
    "typhoid_q1": [
        "belly pain",
        "stomach pain",
        "abdominal pain",
        "abdomen pain",
        "stomach ache",
        "belly ache",
        "tenderness in stomach",
        "cramping in stomach",
        "sakit ng tiyan",
        "pananakit ng tiyan",
        "masakit ang tiyan",
        "paninikip ng tiyan",
    ],
    "typhoid_q2": [
        "constipation",
        "can't poop",
        "loose stool",
        "loose stools",
        "watery stool",
        "diarrhea",
        "diarrhoea",
        "pagtatae",
        "pagtitibi",
        "tibi",
        "maluwag na pagdumi",
    ],
    "typhoid_q3": [
        "fever lasting",
        "fever for days",
        "fever getting worse",
        "persistent fever",
        "lagnat na tumatagal",
        "tumataas na lagnat",
        "lagnat na lumalala",
    ],
    "typhoid_q4": [
        "rose spots",
        "pink spots",
        "faint pink spots",
        "faint red spots",
        "spots on chest",
        "spots on stomach",
        "maputlang rosas na pantal",
        "pulang pantal sa dibdib",
        "pulang pantal sa tiyan",
    ],
    "typhoid_q5": [
        "pulse slow",
        "slow pulse",
        "slow heartbeat",
        "heart rate slow",
        "mabagal ang tibok",
        "mabagal ang puso",
    ],
    "typhoid_q6": [
        "frontal headache",
        "constant headache",
        "pain in forehead",
        "pananakit sa harap ng ulo",
        "tuloy-tuloy na sakit ng ulo",
    ],
    "typhoid_q7": [
        "loss of appetite",
        "lost appetite",
        "no appetite",
        "don't want to eat",
        "don't feel like eating",
        "nawalan ng gana",
        "walang gana kumain",
        "ayaw kumain",
    ],
    "typhoid_q8": [
        "brain fog",
        "confusion",
        "confused",
        "disoriented",
        "trouble thinking",
        "pagkalito",
        "malabong pag-iisip",
        "hindi makaisip ng maayos",
    ],
    "typhoid_q9": [
        "symptoms started gradually",
        "started slowly",
        "slow onset",
        "built up over days",
        "unti-unting nagsimula",
        "unahan ang sintomas",
    ],
    "typhoid_q10": [
        "severe cough",
        "breathing problems",
        "trouble breathing",
        "matinding ubo",
        "problema sa paghinga",
    ],
    # ── Dengue ───────────────────────────────────────────────────────
    "dengue_q1": [
        "high fever",
        "extremely high fever",
        "very high fever",
        "temperature over",
        "mataas na lagnat",
        "napakataas na lagnat",
        "nilalagnat ng matindi",
    ],
    "dengue_q2": [
        "severe muscle aches",
        "severe body aches",
        "muscle pain",
        "body aches",
        "bone pain",
        "bones breaking",
        "breakbone fever",
        "matinding pananakit ng kalamnan",
        "matinding sakit ng katawan",
        "parang namamali ang buto",
    ],
    "dengue_q3": [
        "pain behind eyes",
        "pain behind the eyes",
        "eye pain",
        "retro-orbital pain",
        "sakit sa likod ng mata",
        "pananakit ng likod ng mata",
        "masakit ang likod ng mata",
    ],
    "dengue_q4": [
        "bleeding gums",
        "nosebleed",
        "nose bleed",
        "mild bleeding",
        "unusual bleeding",
        "gums bleeding",
        "pagdurugo ng gilagid",
        "nosebleed",
        "di-pangkaraniwang pagdurugo",
    ],
    "dengue_q5": [
        "tiny red spots",
        "red spots on skin",
        "rash with spots",
        "petechiae",
        "pantal na may pulang tuldok",
        "maliliit na pulang spot",
    ],
    "dengue_q6": [
        "severe headache",
        "pounding headache",
        "splitting headache",
        "intense headache",
        "matinding sakit ng ulo",
        "napakasakit ng ulo",
    ],
    "dengue_q7": [
        "feel nauseous",
        "nausea",
        "nauseous",
        "want to vomit",
        "feel like vomiting",
        "pagduduwal",
        "pagsusuka",
        "nasusuka",
    ],
    "dengue_q8": [
        "extreme fatigue",
        "overwhelming fatigue",
        "extreme weakness",
        "very tired",
        "completely exhausted",
        "matinding pagkapagod",
        "sobrang pagod",
        "matinding panghihina",
    ],
    "dengue_q9": [
        "stiff joints",
        "sore joints",
        "joint pain",
        "pain in joints",
        "stiffness in joints",
        "paninigas ng kasukasuan",
        "pananakit ng kasukasuan",
    ],
    "dengue_q10": [
        "runny nose",
        "stuffy nose",
        "cough and colds",
        "ubo o sipon",
        "sipon",
        "ubuhin",
    ],
    # ── Pneumonia ────────────────────────────────────────────────────
    "pneumonia_q1": [
        "wet cough",
        "cough with phlegm",
        "thick phlegm",
        "colored phlegm",
        "coughing up mucus",
        "ubo na may plema",
        "makapal na plema",
        "may kulay na plema",
    ],
    "pneumonia_q2": [
        "chest pain when breathing",
        "chest pain when coughing",
        "sharp chest pain",
        "pain in chest",
        "matalim na pananakit ng dibdib",
        "pananakit ng dibdib kapag humihinga",
    ],
    "pneumonia_q3": [
        "shortness of breath",
        "difficulty breathing",
        "hard to breathe",
        "can't breathe well",
        "breathing difficulty",
        "hirap huminga",
        "nahihirapan huminga",
        "kapos ang hininga",
    ],
    "pneumonia_q4": [
        "fever with chills",
        "persistent fever with chills",
        "fever and shivering",
        "tuloy-tuloy na lagnat na may panginginig",
        "lagnat na may ginaw",
    ],
    "pneumonia_q5": [
        "runny nose",
        "sniffles",
        "nose running",
        "nasal discharge",
        "sipon",
        "pagsinga",
        "tumutulo ang ilong",
    ],
    "pneumonia_q6": [
        "extreme weakness",
        "no energy",
        "completely drained",
        "matinding panghihina",
        "walang lakas",
    ],
    "pneumonia_q7": [
        "body aches",
        "muscle aches",
        "body pain",
        "muscle pain",
        "pananakit ng katawan",
        "pananakit ng kalamnan",
    ],
    "pneumonia_q8": [
        "feel nauseous",
        "nausea",
        "nauseous",
        "vomiting",
        "throwing up",
        "pagduduwal",
        "pagsusuka",
    ],
    "pneumonia_q9": [
        "persistent headache",
        "constant headache",
        "headache that won't go away",
        "tuloy-tuloy na sakit ng ulo",
    ],
    "pneumonia_q10": [
        "worse when lying down",
        "breathing worse lying down",
        "can't breathe lying down",
        "hirap huminga kapag nakahiga",
        "lumalala ang paghinga kapag nakahiga",
    ],
    # ── Diarrhea ─────────────────────────────────────────────────────
    "diarrhea_q1": [
        "watery stool",
        "watery stools",
        "loose stool",
        "loose stools",
        "frequent diarrhea",
        "madalas na pagtatae",
        "matubig na dumi",
        "malabnaw na dumi",
    ],
    "diarrhea_q2": [
        "severe stomach cramps",
        "bad stomach cramps",
        "severe abdominal pain",
        "matinding pulikat",
        "matinding pananakit ng tiyan",
    ],
    "diarrhea_q3": [
        "signs of dehydration",
        "very thirsty",
        "dry mouth",
        "not peeing much",
        "low urine",
        "mga palatandaan ng dehydration",
        "uhaw na uhaw",
    ],
    "diarrhea_q4": [
        "blood in stool",
        "blood in poop",
        "red streaks in stool",
        "bloody stool",
        "dugo sa dumi",
        "may dugo ang dumi",
    ],
    "diarrhea_q5": [
        "cough and runny nose",
        "cough with runny nose",
        "breathing difficulty",
        "ubo at sipon",
        "hirap sa paghinga",
    ],
    "diarrhea_q6": [
        "high fever lasting",
        "fever lasting over a week",
        "fever getting worse for days",
        "lagnat na tumatagal nang mahigit isang linggo",
    ],
    "diarrhea_q7": [
        "feel nauseous",
        "nausea",
        "nauseous",
        "vomiting",
        "throwing up",
        "pagduduwal",
        "pagsusuka",
    ],
    "diarrhea_q8": [
        "extreme weakness from fluid loss",
        "weakness from dehydration",
        "drained from diarrhea",
        "matinding panghihina dahil sa pagtatae",
    ],
    "diarrhea_q9": [
        "mild fever",
        "slight fever",
        "low-grade fever",
        "bahagyang lagnat",
        "mediyo may lagnat",
    ],
    "diarrhea_q10": [
        "sudden urge to go",
        "can't hold it",
        "sudden need to use bathroom",
        "uncontrollable urge",
        "biglang matinding pagnanais na dumumi",
    ],
    # ── Measles ──────────────────────────────────────────────────────
    "measles_q1": [
        "rash started on face",
        "rash spreading from face",
        "rash spreading downward",
        "rash from head down",
        "pantal na nagsimula sa mukha",
        "kumalat pababa ang pantal",
    ],
    "measles_q2": [
        "high fever with dry cough",
        "fever and cough",
        "persistent dry cough",
        "mataas na lagnat na may tuyong ubo",
        "tuyong ubo",
    ],
    "measles_q3": [
        "red eyes",
        "watery eyes",
        "light sensitive eyes",
        "eyes sensitive to light",
        "red and watery eyes",
        "namumula ang mata",
        "sensitibo sa liwanag ang mata",
    ],
    "measles_q4": [
        "fever before rash",
        "cough before rash",
        "runny nose before rash",
        "nauna ang lagnat bago ang pantal",
        "sipon bago lumabas ang pantal",
    ],
    "measles_q5": [
        "constant runny nose",
        "always runny nose",
        "nose won't stop running",
        "tuloy-tuloy na sipon",
        "hindi tumitigil ang sipon",
    ],
    "measles_q6": [
        "white spots in mouth",
        "spots inside mouth",
        "koplik spots",
        "putting spots sa bibig",
        "maliliit na puting spot sa bibig",
    ],
    "measles_q7": [
        "unusual bleeding",
        "severe deep bone pain",
        "bleeding from gums",
        "di-pangkaraniwang pagdurugo",
        "matinding pananakit ng buto",
    ],
    "measles_q8": [
        "complete exhaustion",
        "completely drained",
        "totally exhausted",
        "matinding pagkapagod",
        "sobrang pagod na sobra",
    ],
    "measles_q9": [
        "sore throat",
        "scratchy throat",
        "painful throat",
        "masakit ang lalamunan",
        "nakakati ang lalamunan",
    ],
    "measles_q10": [
        "mild diarrhea",
        "slight diarrhea",
        "loose stools",
        "bahagyang pagtatae",
        "mediyo pagtatae",
    ],
    # ── Influenza ────────────────────────────────────────────────────
    "influenza_q1": [
        "symptoms started suddenly",
        "came on suddenly",
        "sudden onset",
        "started all at once",
        "biglang nagsimula",
        "bigla-bigla",
    ],
    "influenza_q2": [
        "dry cough",
        "hacking cough",
        "persistent cough",
        "tuyong ubo",
        "paulit-ulit na ubo",
    ],
    "influenza_q3": [
        "body aches all over",
        "aches all over",
        "pain all over body",
        "whole body aches",
        "pananakit ng katawan sa kabuuan",
        "sakit ang buong katawan",
    ],
    "influenza_q4": [
        "extreme tiredness",
        "exhaustion",
        "very exhausted",
        "completely worn out",
        "matinding pagod",
        "sobrang pagod",
    ],
    "influenza_q5": [
        "headache",
        "pain in head",
        "splitting headache",
        "sakit ng ulo",
        "pananakit ng ulo",
    ],
    "influenza_q6": [
        "sore throat",
        "scratchy throat",
        "throat hurts",
        "masakit ang lalamunan",
        "makating lalamunan",
    ],
    "influenza_q7": [
        "runny nose",
        "stuffy nose",
        "congestion",
        "nasal congestion",
        "sipon",
        "baradong ilong",
    ],
    "influenza_q8": [
        "skin rash",
        "rash on body",
        "pain behind eyes",
        "rash o pananakit sa likod ng mata",
        "pantal sa balat",
    ],
    "influenza_q9": [
        "cough stays dry",
        "dry cough no phlegm",
        "cough without colored phlegm",
        "nananatiling tuyo ang ubo",
        "walang plema ang ubo",
    ],
    "influenza_q10": [
        "breathing is fine",
        "no chest pain",
        "breathing normally",
        "no sharp chest pain",
        "maayos ang paghinga",
        "walang pananakit ng dibdib",
    ],
}
